import { Host } from "./tauri-bridge";

// A terminal tab's split layout is a binary tree (tmux/i3-style): every
// leaf is one independent SSH connection, every split is a single divider
// between exactly two regions, recursively splittable. This replaces a
// flat panes array specifically so panes can be resized independently of
// each other and "Split" can target one specific pane instead of just
// appending to the tab.
export interface PaneLeaf {
  type: "leaf";
  paneId: string;
  host: Host;
}

export interface PaneSplit {
  type: "split";
  splitId: string;
  // "row": children sit side by side (a vertical divider between them).
  // "column": children stack (a horizontal divider) - matches flexbox's
  // own flex-direction naming so the renderer maps onto it directly.
  direction: "row" | "column";
  // 0-1, the fraction of space "a" gets; "b" gets the rest.
  ratio: number;
  a: PaneNode;
  b: PaneNode;
}

export type PaneNode = PaneLeaf | PaneSplit;

const MIN_RATIO = 0.15;
const MAX_RATIO = 0.85;

export function countLeaves(node: PaneNode): number {
  return node.type === "leaf" ? 1 : countLeaves(node.a) + countLeaves(node.b);
}

export function findLeaf(node: PaneNode, paneId: string): PaneLeaf | null {
  if (node.type === "leaf") return node.paneId === paneId ? node : null;
  return findLeaf(node.a, paneId) ?? findLeaf(node.b, paneId);
}

export function collectLeaves(node: PaneNode): PaneLeaf[] {
  return node.type === "leaf" ? [node] : [...collectLeaves(node.a), ...collectLeaves(node.b)];
}

// Replaces the leaf identified by `paneId` with a new split whose two
// children are the original leaf (unchanged) and a fresh leaf for
// `newHost` under `newPaneId` (generated by the caller, not here, so the
// caller can hand the id back to whoever needs it without needing to diff
// the tree afterward). paneId is unique across the whole tree, so
// recursing into both children is safe - only the branch that actually
// contains it produces a different node.
export function splitLeaf(
  node: PaneNode,
  paneId: string,
  direction: "row" | "column",
  newPaneId: string,
  newHost: Host,
): PaneNode {
  if (node.type === "leaf") {
    if (node.paneId !== paneId) return node;
    return {
      type: "split",
      splitId: crypto.randomUUID(),
      direction,
      ratio: 0.5,
      a: node,
      b: { type: "leaf", paneId: newPaneId, host: newHost },
    };
  }
  return {
    ...node,
    a: splitLeaf(node.a, paneId, direction, newPaneId, newHost),
    b: splitLeaf(node.b, paneId, direction, newPaneId, newHost),
  };
}

// Removes the leaf identified by `paneId`, collapsing its parent split
// into just the surviving sibling (standard BSP close - the tree gets one
// level shallower exactly at that spot, nothing else changes). Returns
// null if `node` itself is only that one leaf - callers must guard against
// removing a tab's only remaining pane themselves (route to closing the
// whole tab instead), same as before this tree model existed.
export function removeLeaf(node: PaneNode, paneId: string): PaneNode | null {
  if (node.type === "leaf") {
    return node.paneId === paneId ? null : node;
  }
  if (findLeaf(node.a, paneId)) {
    const removed = removeLeaf(node.a, paneId);
    return removed === null ? node.b : { ...node, a: removed };
  }
  if (findLeaf(node.b, paneId)) {
    const removed = removeLeaf(node.b, paneId);
    return removed === null ? node.a : { ...node, b: removed };
  }
  return node;
}

export function resizeSplit(node: PaneNode, splitId: string, newRatio: number): PaneNode {
  if (node.type === "leaf") return node;
  if (node.splitId === splitId) return { ...node, ratio: Math.max(MIN_RATIO, Math.min(MAX_RATIO, newRatio)) };
  return { ...node, a: resizeSplit(node.a, splitId, newRatio), b: resizeSplit(node.b, splitId, newRatio) };
}

export interface Rect {
  left: number;
  top: number;
  width: number;
  height: number;
}

export interface LeafLayout {
  paneId: string;
  host: Host;
  rect: Rect;
}

export interface DividerLayout {
  splitId: string;
  direction: "row" | "column";
  ratio: number;
  // The pixel size available to divide between "a" and "b" *excluding* the
  // divider's own thickness - what PaneResizeDivider needs to convert a
  // drag's pixel delta into a ratio delta.
  availablePx: number;
  rect: Rect;
}

export const DIVIDER_THICKNESS_PX = 6;

// Flattens the tree into absolute-pixel leaf/divider rects for a given
// container rect. This is what lets every pane render as a flat list of
// siblings (see PaneSplitView.tsx) instead of nested DOM per split level -
// nesting per level means a leaf's ancestor chain changes shape whenever a
// *different* pane elsewhere in the tree is split or closed, and React
// unmounts/remounts a component whenever its own rendered element type
// changes (a split collapsing into its surviving leaf child changes that
// return type from a wrapper div to a bare TerminalView) - which was
// silently killing and reconnecting unrelated panes' SSH sessions. A flat
// list keyed by paneId/splitId sidesteps this entirely: closing or
// splitting a pane only ever changes the *rects* other panes get, never
// their identity or position in the render tree.
export function computeLayout(node: PaneNode, rect: Rect): { leaves: LeafLayout[]; dividers: DividerLayout[] } {
  if (node.type === "leaf") {
    return { leaves: [{ paneId: node.paneId, host: node.host, rect }], dividers: [] };
  }
  const isRow = node.direction === "row";
  const total = isRow ? rect.width : rect.height;
  const availablePx = Math.max(0, total - DIVIDER_THICKNESS_PX);
  const aSize = availablePx * node.ratio;
  const bSize = availablePx - aSize;
  const aRect: Rect = isRow ? { ...rect, width: aSize } : { ...rect, height: aSize };
  const dividerRect: Rect = isRow
    ? { left: rect.left + aSize, top: rect.top, width: DIVIDER_THICKNESS_PX, height: rect.height }
    : { left: rect.left, top: rect.top + aSize, width: rect.width, height: DIVIDER_THICKNESS_PX };
  const bRect: Rect = isRow
    ? { left: rect.left + aSize + DIVIDER_THICKNESS_PX, top: rect.top, width: bSize, height: rect.height }
    : { left: rect.left, top: rect.top + aSize + DIVIDER_THICKNESS_PX, width: rect.width, height: bSize };
  const aLayout = computeLayout(node.a, aRect);
  const bLayout = computeLayout(node.b, bRect);
  return {
    leaves: [...aLayout.leaves, ...bLayout.leaves],
    dividers: [
      ...aLayout.dividers,
      { splitId: node.splitId, direction: node.direction, ratio: node.ratio, availablePx, rect: dividerRect },
      ...bLayout.dividers,
    ],
  };
}

// Wire format for persisting a layout in a Workspace (see
// workspace_tabs.layout_json) - host ids, not embedded Host objects,
// mirroring how every other cross-entity reference in this schema is an
// id. paneId/splitId are dropped entirely (regenerated fresh on restore,
// see deserializeLayout) since they must stay unique only among currently
// open panes, not across saves.
export type SerializedPaneNode =
  | { type: "leaf"; hostId: string }
  | { type: "split"; direction: "row" | "column"; ratio: number; a: SerializedPaneNode; b: SerializedPaneNode };

export function serializeLayout(node: PaneNode): SerializedPaneNode {
  if (node.type === "leaf") return { type: "leaf", hostId: node.host.id };
  return {
    type: "split",
    direction: node.direction,
    ratio: node.ratio,
    a: serializeLayout(node.a),
    b: serializeLayout(node.b),
  };
}

// Inverse of serializeLayout. A leaf whose host was deleted since the
// workspace was saved resolves to null; a split with one dead child
// collapses to just the surviving child (same shape as removeLeaf's
// collapse), and a split with both children dead collapses to null in
// turn. Returns null only if nothing in the whole tree survived.
export function deserializeLayout(raw: SerializedPaneNode, hostsById: Map<string, Host>): PaneNode | null {
  if (raw.type === "leaf") {
    const host = hostsById.get(raw.hostId);
    return host ? { type: "leaf", paneId: crypto.randomUUID(), host } : null;
  }
  const a = deserializeLayout(raw.a, hostsById);
  const b = deserializeLayout(raw.b, hostsById);
  if (a && b) return { type: "split", splitId: crypto.randomUUID(), direction: raw.direction, ratio: raw.ratio, a, b };
  return a ?? b;
}
